name: Restore GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  restore_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm Actions is enabled
        run: echo "GitHub Actions should now be active"
